version: "3.8"

include:
  - ./docker/common.yml
  - ./docker/keycloak.yml

services:
  producer-micro:
    build:
      context: ./microservices
      dockerfile: producer/Dockerfile
    image: producer-micro:latest
    hostname: producer-micro
    container_name: producer-micro
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/producer/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - learning
