version: "3.8"

include:
  - ./docker/common.yml
  - ./docker/keycloak.yml

services:
  common-image:
    build:
      context: ./microservices
      dockerfile: Dockerfile
    image: microservices-setup:latest

  config-server:
    build:
      context: ./microservices
      dockerfile: config-server/Dockerfile
    image: config-server:latest
    hostname: config-server
    container_name: config-server
    ports:
      - "9081:9081"
    depends_on:
      common-image:
        condition: service_completed_successfully
    healthcheck:
      test: "curl --fail --silent localhost:9081/configserver/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 3s
    secrets:
      - source: dev_github_pass
        target: DEV_GITHUB_PASS
    networks:
      - learning

  producer-micro:
    build:
      context: ./microservices
      dockerfile: producer/Dockerfile
    image: producer-micro:latest
    hostname: producer-micro
    container_name: producer-micro
    ports:
      - "8080:8080"
    depends_on:
      common-image:
        condition: service_completed_successfully
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/producer/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s
    environment:
      - MICRO-PRODUCER_KEYCLOAK_HOST=keycloak:8080
      - SPRING_CLOUD_CONFIG_HOST=config-server:9081/configserver
    secrets:
      - source: dev_oauth_microservice_client_secret
        target: DEV_OAUTH_MICROSERVICE-CLIENT
    networks:
      - learning
