version: "3.8"

include:
  - ./docker/common.yml
  - ./docker/keycloak.yml

services:
  config-server:
    build:
      context: ./microservices
      dockerfile: config-server/Dockerfile
    image: config-server:latest
    hostname: config-server
    container_name: config-server
    ports:
      - "9081:9081"
    healthcheck:
      test: "curl --fail --silent localhost:9081/configserver/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 3s
    environment:
      - DEV_GITHUB_PASS=/run/secrets/dev_github_pass.txt
    secrets:
      - dev_github_pass
    networks:
      - learning

  producer-micro:
    build:
      context: ./microservices
      dockerfile: producer/Dockerfile
    image: producer-micro:latest
    hostname: producer-micro
    container_name: producer-micro
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    healthcheck:
      test: "curl --fail --silent localhost:8080/producer/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 3s
    environment:
      - DEV_OAUTH_MICROSERVICE-CLIENT=/run/secrets/dev_oauth_microservice_client_secret
      - MICRO-PRODUCER_KEYCLOAK_HOST=keycloak:8080
      - SPRING_CLOUD_CONFIG_HOST=config-server:9081/configserver
    secrets:
      - dev_oauth_microservice_client_secret
    networks:
      - learning
