dep-auth:
  secrets:
    microservice-client:
      client-secret: ${DEV_OAUTH_MICROSERVICE-CLIENT}
  keycloak:
    host: localhost:9080
    realm: microservices_realm

spring:
  config:
    import: optional:configtree:/run/secrets/
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://${dep-auth.keycloak.host:-localhost:9080}/realms/${dep-auth.keycloak.realm}/protocol/openid-connect/certs
  # This mode is only available on local, on docker containers it raises an error due to how the token is generated
  #
  #        opaque-token:
  #          introspection-uri: http://${dep-auth.keycloak.host:-localhost:9080}/realms/${dep-auth.keycloak.realm}/protocol/openid-connect/token/introspect
  #          client-id: microservice-client
  #          client-secret: ${micro-producer.secrets.microservice-client.client-secret}
