spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka-0:9092
            - kafka-1:9092
            - kafka-2:9092
          configuration:
            schema:
              registry:
                url: http://schema-registry:9091
