spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9094
            - localhost:9095
            - localhost:9096
          configuration:
            schema:
              registry:
                url: http://localhost:9091
