spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:6668
            - localhost:6666
            - localhost:6667
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
            schema:
              registry:
                url: http://localhost:9091
            value:
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          enableObservation: true