auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka-0:9092,kafka-1:9092,kafka-2:9092
    name: microservices-setup
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
