version: "3.8"

services:
  keycloak-database:
    image: postgres:16
    container_name: keycloak-database
    hostname: keycloak-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: learning-keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - learning

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./data/keycloak:/opt/keycloak/data/
    ports:
      - "9080:8080"
    command:
      - start-dev
    depends_on:
      keycloak-database:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/learning-keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: "timeout 10s bash -c ':> /dev/tcp/localhost/8080'"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - learning

volumes:
  postgres_data: