version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9070:9090"
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - learning

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    hostname: zipkin
    ports:
      - "9071:9411"
    networks:
      - learning

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "9072:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - learning

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    hostname: loki
    ports:
      - "9073:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki:/loki
    networks:
      - learning

volumes:
  loki: { }
  grafana: { }
  prometheus: { }