server:
  port: 8080
  servlet:
    context-path: /producer

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/microservices_realm/protocol/openid-connect/certs