spring:
  application:
    name: producer
  #    profiles:
  #      active: local
  config:
    import: optional:configserver:http://${spring.cloud.config.host}
  cloud:
    config:
      enabled: true
      host: localhost:9081/configserver
      name: producer
      profile: config,config_dev
      label: feature(_)spring-config-server
