tools:
  kafka:
    enabled: false
  oauth2:
    enabled: false
  observability:
    enabled: false
  config-server:
    enabled: false

micro-producer:
  property: local-value

spring:
  cloud:
    config:
      host: localhost:9081/configserver
