server:
  port: 8080
  servlet:
    context-path: /producer

tools:
  kafka:
    enabled: false
  oauth2:
    enabled: true
  observability:
    enabled: true
  config-server:
    enabled: true

micro-producer:
  random:
    keys:
      - "Kafka"
      - "diaavlo"
      - "no fuimo"
  property: generic value


spring:
  profiles:
    active: local
  application:
    name: producer
  config:
    import: optional:configserver:http://${spring.cloud.config.host}
  cloud:
    config:
      enabled: false
    #      host: localhost:9081/configserver
    #      name: producer
    #      profile: config
    # This property allows us to establish a branch inside the git repository to check out the configuration
    #      label: feature(_)spring-config-server

    stream:
      bindings:
        my-message-producer-out-0:
          producer:
            useNativeEncoding: true
            poller:
              fixed-delay: 15000
          destination: learning.stoopid-topic
          content-type: application/*+avro
