micro-producer:
  keycloak:
    host: localhost:9080
  property: local-value

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9071/api/v2/spans

spring:
  config:
    import: optional:configserver:http://${spring.cloud.config.host}
  zipkin:
    base-url: http://zipkin:9411/
  cloud:
    config:
      host: localhost:9081/configserver
    stream:
      kafka:
        binder:
          configuration:
            schema.registry.url: http://localhost:9091
          brokers:
            - localhost:9094
            - localhost:9095
            - localhost:9096
