micro-producer:
  keycloak:
    host: keycloak:8080
  property: docker value


spring:
  config:
    import: optional:configserver:http://${spring.cloud.config.host},optional:configtree:/run/secrets/

  cloud:
    config:
      host: config-server:9081/configserver
    stream:
      bindings:
      kafka:
        binder:
          configuration:
            schema.registry.url: http://schema-registry:9091
          brokers:
            - kafka-0:9092
            - kafka-1:9092
            - kafka-2:9092
