micro-producer:
  keycloak:
    host: keycloak:8080
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  property: docker value

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  config:
    import: optional:configserver:http://${spring.cloud.config.host},optional:configtree:/run/secrets/
  cloud:
    config:
      host: config-server:9081/configserver
