micro-producer:
  keycloak:
    host: localhost:9080
  loki:
    endpoint: http://localhost:9073/loki/api/v1/push
  property: local-value

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9071/api/v2/spans

spring:
  config:
    import: optional:configserver:http://${spring.cloud.config.host}
  cloud:
    config:
      host: localhost:9081/configserver
