server:
  port: 9081
  servlet:
    context-path: /configserver

config-server:
  secrets:
    git-password: ${DEV_GITHUB_PASS}

spring:
  config:
    import: optional:configtree:/run/secrets/

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dferreiropresedo/microservices-setup
          username: dferreiropresedo
          password: ${config-server.secrets.git-password}
          defaultLabel: main
          search-paths:
            - 'configbase/{application}'
