server:
  port: 9081
  servlet:
    context-path: /configserver

config-server:
  secrets:
    git-password: ${DEV_GITHUB_PASS}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dferreiropresedo/microservices-setup/configbase
          username: dferreiropresedo
          password: ${config-server.secrets.git-password}
          defaultLabel: main
          repos:
            producer:
              pattern: producer
              uri: https://github.com/dferreiropresedo/microservices-setup/configbase/producer