server:
  port: 9081
  servlet:
    context-path: /configserver

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG


config-server:
  secrets:
    git-password: ${DEV_GITHUB_PASS}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dferreiropresedo/microservices-setup
          username: dferreiropresedo
          password: ${config-server.secrets.git-password}
          defaultLabel: main
          search-paths:
            - 'configbase/{application}'
