server:
  port: 8081
  servlet:
    context-path: /consumer

tools:
  kafka:
    enabled: true
  oauth2:
    enabled: true
  observability:
    enabled: true
  config-server:
    enabled: true

spring:
  profiles:
    active: local
  application:
    name: consumer
  config:
    import: optional:configserver:http://${spring.cloud.config.host}

  cloud:
    config:
      enabled: false
    #      host: localhost:9081/configserver
    #      name: consumer
    #      profile: config
    stream:
      bindings:
        my-message-consumer-in-0:
          consumer:
            useNativeEncoding: true
            startOffset: latest
          destination: learning.stoopid-topic
          group: consumer-microservice
          content-type: application/*+avro
