micro-producer:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  config:
    import: optional:configserver:http://${spring.cloud.config.host},optional:configtree:/run/secrets/
  cloud:
    config:
      host: config-server:9081/configserver
    stream:
      kafka:
        binder:
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://schema-registry:9091
          brokers:
            - kafka-0:9092
            - kafka-1:9092
            - kafka-2:9092
