server:
  port: 8081
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer
  config:
    import: optional:configserver:http://${spring.cloud.config.host},optional:configtree:/run/secrets/

  cloud:
    config:
      enabled: false
      host: localhost:9081/configserver
      name: consumer
      profile: config
    stream:
      bindings:
        my-message-consumer-in-0:
          consumer:
            startOffset: latest
            instanceCount: 3
          destination: learning.stoopid-topic
          group: consumer-microservice
      kafka:
        binder:
          brokers:
            - localhost:9094
            - localhost:9095
            - localhost:9096
